import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { message, history = [] } = await request.json();

    // Construct the content array with history and the new message
    const contentArray = [
      ...history.map((msg: any) => ({
        role: msg.role,
        parts: [{ text: msg.content }]
      })),
      {
        role: 'user',
        parts: [{ text: message }]
      }
    ];

    const response = await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=AIzaSyAko4MMET276Td7MoaPu4AtrEd4QLhlg_A', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: contentArray
      })
    });

    const data = await response.json();

    if (!response.ok) {
      console.error('Gemini API Error:', data);
      return NextResponse.json(
        { error: data.error?.message || 'Failed to get response from Gemini API' },
        { status: response.status }
      );
    }

    // Check for candidates in the response
    if (!data.candidates || !Array.isArray(data.candidates) || data.candidates.length === 0) {
      console.error('No candidates in response:', data);
      if (data.promptFeedback?.blockReason) {
        return NextResponse.json(
          { error: `Request blocked: ${data.promptFeedback.blockReason}` },
          { status: 400 }
        );
      }
      return NextResponse.json(
        { error: 'No response generated by the model' },
        { status: 500 }
      );
    }

    const aiText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (typeof aiText !== 'string') {
      console.error('Invalid response format:', data);
      return NextResponse.json(
        { error: 'Invalid response format from Gemini API' },
        { status: 500 }
      );
    }

    return NextResponse.json({ response: aiText });
  } catch (error) {
    console.error('Error in Gemini API route:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal server error' },
      { status: 500 }
    );
  }
}