import { useState, useCallback } from 'react';

interface Message {
  role: 'user' | 'model';
  content: string;
}

export const useGeminiChat = (apiKey: string) => {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const sendMessage = useCallback(async (message: string, history: Message[] = []): Promise<string> => {
    setIsLoading(true);
    setError(null);

    try {
      // Construct the content array with history and the new message
      const contentArray = [
        ...history.map(msg => ({
          role: msg.role,
          parts: [{ text: msg.content }]
        })),
        {
          role: 'user',
          parts: [{ text: message }]
        }
      ];

      console.log('Sending request to Gemini API:', {
        contents: contentArray
      });

      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: contentArray
        })
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        console.error('Gemini API Error Response:', errorData);
        throw new Error(errorData.error?.message || `API request failed with status ${response.status}`);
      }

      const data = await response.json();
      console.log('Gemini API Response:', data);

      // Check for candidates in the response
      if (!data.candidates || !Array.isArray(data.candidates) || data.candidates.length === 0) {
        console.error('No candidates in response:', data);
        if (data.promptFeedback?.blockReason) {
          throw new Error(`Request blocked: ${data.promptFeedback.blockReason}`);
        }
        throw new Error('No response generated by the model');
      }

      const aiText = data.candidates?.[0]?.content?.parts?.[0]?.text;

      if (typeof aiText !== 'string') {
        console.error('Invalid response format:', data);
        throw new Error('Invalid response format from Gemini API');
      }

      return aiText;
    } catch (err) {
      console.error('Gemini API Error:', err);
      const errorMessage = err instanceof Error ? err.message : 'An unknown error occurred';
      setError(errorMessage);
      throw err;
    } finally {
      setIsLoading(false);
    }
  }, [apiKey]);

  return { sendMessage, isLoading, error };
};